spring:
  application:
    name: @spring.application.name@
    version: @spring.application.version@
  profiles:
    active: @profiles.active@
  trace-id: @trace.id.name@
  trace-uri: @trace.uri.name@

# 日志配置
logging:
  level:
    cn.lbcmmszdntnt: @logging.level@
    org.springframework: warn
    tech.powerjob.worker.background: warn
  config: classpath:logback-spring.xml

# mp设置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml # Mapper.xml文件地址,默认值
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler #设置枚举处理器
    map-underscore-to-camel-case: true # 是否开启下划线和驼峰的映射
    cache-enabled: false # 是否开启二级缓存
  global-config:
    db-config:
      logic-delete-field: idDeleted
      logic-delete-value: 1 #逻辑已删除值(默认为1)
      logic-not-delete-value: 0 #逻辑未删除值(默认为0)
      id-type: auto #id为雪花算法生成 设置为none->为遵循版本默认，可见这个版本默认为assign_id
      update-strategy: not_null #更新策略:只更新非空字段
      insert-strategy: not_null #插入策略:为空走默认值
  db-type: MYSQL # 分页时指定数据库类型

media:
  map: media/
  static: static/
  binding: binding/
  swagger: swagger/
  login: login/
  photo: photo/
  invite: invite/
  common: common/
  medal: medal/

okr:
  service:
    okrOperateServiceMap:
      scene-p: personalOkrServiceImpl
      scene-t: teamOkrServiceImpl
      scene-tp: teamPersonalOkrServiceImpl
    loginServiceMap:
      WX_JWT: wxLoginServiceImpl
      EMAIL_JWT: emailLoginServiceImpl
    inviteQRCodeServiceMap:
      wx: wxInviteQRCodeServiceImpl
      web: webInviteQRCodeServiceImpl
    teamAchievementServiceMap:
      0: longTermAchievementServiceImpl
      1: shortTermAchievementServiceImpl
      2: shortTermAchievementServiceImpl
    taskServiceMap:
      0: actionServiceImpl
      1: priorityNumberOneServiceImpl
      2: priorityNumberTwoServiceImpl
    dayRecordCompleteServiceMap:
      0: dayRecordServiceThirdImpl
      1: dayRecordServiceSecondImpl
      2: dayRecordServiceSecondImpl

medal:
  status-flag:
    statusFlagProperties:
      - color: "#000000"
        credit: 80
      - color: "#000001"
        credit: 50
      - color: "#000002"
        credit: 20
    threshold: 60
  stay-true-beginning:
    id: 1
    coefficient: 0
  harvest-achievement:
    id: 2
    coefficient: 60
  stand-out-crowd:
    id: 3
    coefficient: 1
  victory-within-grasp:
    id: 4
    coefficient: 1
  short-term-achievement:
    id: 5
    coefficient: 5
  long-term-achievement:
    id: 6
    coefficient: 2
  great-state:
    id: 7
    coefficient: 1


font:
  path: /static/XiangJiaoDaJiangJunLingGanTi-2.ttf
  board: /static/board.png
  text:
    color:
      r: 43
      g: 90
      b: 103
    common: "[come on]"
    invite: "[invite]"
    binding: "[BINDING]"
    login: "[LOGIN]"


xxl:
  job:
    url:
      login: /login
      groupPageList: /jobgroup/pageList
      infoPageList: /jobinfo/pageList
      groupSave: /jobgroup/save
      infoAdd: /jobinfo/add
      infoStart: /jobinfo/start
      infoIds: /jobinfo/ids
      infoStopIds: /jobinfo/stopids
      infoRemove: /jobinfo/remove
      infoStop: /jobinfo/stop
      infoUpdate: /jobinfo/update


limit:
  time:
    second: 86400
    multiple: 2
resource:
  compression:
    threshold: 65536
  upload:
    max-file-size: 20
    max-request-size: 100
    data-unit: megabytes


secure:
  custom:
    list:
      - urls:
          - /doc.html/**
          - /v3/api-docs/**
          - /webjars/**
          - /error
          - /favicon.ico
          - /swagger-resources/**
          - /swagger-ui/**
          - /swagger-ui.html/**
        properties:
          permit:
          authenticate: false
          authorize: false
      # websocket 接口在这里配置拦截参数
      - urls:
          - /web/wxloginws
        properties:
          permit:
          authenticate: false
          authorize: false

  ignored:
    urls: # 安全路径白名单
      - /doc.html/**
      - /v3/api-docs/**
      - /webjars/**
      - /error
      - /favicon.ico
      - /swagger-resources/**
      - /swagger-ui/**
      - /swagger-ui.html/**
